#include "syscall.h"
#include <stddef.h>

t_syscall	g_syscall_32[] = {
	[  0] = { 0,	"restart_syscall"			},
	[  1] = { 1,	"exit"						},
	[  2] = { 0,	"fork"						},
	[  3] = { 3,	"read"						},
	[  4] = { 3,	"write"						},
	[  5] = { 3,	"open"						},
	[  6] = { 1,	"close"						},
	[  7] = { 3,	"waitpid"					},
	[  8] = { 2,	"creat"						},
	[  9] = { 2,	"link"						},
	[ 10] = { 1,	"unlink"					},
	[ 11] = { 3,	"execve"					},
	[ 12] = { 1,	"chdir"						},
	[ 13] = { 1,	"time"						},
	[ 14] = { 3,	"mknod"						},
	[ 15] = { 2,	"chmod"						},
	[ 16] = { 3,	"lchown"					},
	[ 17] = { 0,	"break"						},
	[ 18] = { 2,	"oldstat"					},
	[ 19] = { 3,	"lseek"						},
	[ 20] = { 0,	"getpid"					},
	[ 21] = { 5,	"mount"						},
	[ 22] = { 1,	"umount"					},
	[ 23] = { 1,	"setuid"					},
	[ 24] = { 0,	"getuid"					},
	[ 25] = { 1,	"stime"						},
	[ 26] = { 4,	"ptrace"					},
	[ 27] = { 1,	"alarm"						},
	[ 28] = { 2,	"oldfstat"					},
	[ 29] = { 0,	"pause"						},
	[ 30] = { 2,	"utime"						},
	[ 31] = { 2,	"stty"						},
	[ 32] = { 2,	"gtty"						},
	[ 33] = { 2,	"access"					},
	[ 34] = { 1,	"nice"						},
	[ 35] = { 0,	"ftime"						},
	[ 36] = { 0,	"sync"						},
	[ 37] = { 2,	"kill"						},
	[ 38] = { 2,	"rename"					},
	[ 39] = { 2,	"mkdir"						},
	[ 40] = { 1,	"rmdir"						},
	[ 41] = { 1,	"dup"						},
	[ 42] = { 1,	"pipe"						},
	[ 43] = { 1,	"times"						},
	[ 44] = { 0,	"prof"						},
	[ 45] = { 1,	"brk"						},
	[ 46] = { 1,	"setgid"					},
	[ 47] = { 0,	"getgid"					},
	[ 48] = { 2,	"signal"					},
	[ 49] = { 0,	"geteuid"					},
	[ 50] = { 0,	"getegid"					},
	[ 51] = { 1,	"acct"						},
	[ 52] = { 2,	"umount2"					},
	[ 53] = { 0,	"lock"						},
	[ 54] = { 3,	"ioctl"						},
	[ 55] = { 3,	"fcntl"						},
	[ 56] = { 0,	"mpx"						},
	[ 57] = { 2,	"setpgid"					},
	[ 58] = { 2,	"ulimit"					},
	[ 59] = { 1,	"oldolduname"				},
	[ 60] = { 1,	"umask"						},
	[ 61] = { 1,	"chroot"					},
	[ 62] = { 2,	"ustat"						},
	[ 63] = { 2,	"dup2"						},
	[ 64] = { 0,	"getppid"					},
	[ 65] = { 0,	"getpgrp"					},
	[ 66] = { 0,	"setsid"					},
	[ 67] = { 3,	"sigaction"					},
	[ 68] = { 0,	"sgetmask"					},
	[ 69] = { 1,	"ssetmask"					},
	[ 70] = { 2,	"setreuid"					},
	[ 71] = { 2,	"setregid"					},
	[ 72] = { 3,	"sigsuspend"				},
	[ 73] = { 1,	"sigpending"				},
	[ 74] = { 2,	"sethostname"				},
	[ 75] = { 2,	"setrlimit"					},
	[ 76] = { 2,	"getrlimit"					},
	[ 77] = { 2,	"getrusage"					},
	[ 78] = { 2,	"gettimeofday"				},
	[ 79] = { 2,	"settimeofday"				},
	[ 80] = { 2,	"getgroups"					},
	[ 81] = { 2,	"setgroups"					},
	[ 82] = { 1,	"select"					},
	[ 83] = { 2,	"symlink"					},
	[ 84] = { 2,	"oldlstat"					},
	[ 85] = { 3,	"readlink"					},
	[ 86] = { 1,	"uselib"					},
	[ 87] = { 2,	"swapon"					},
	[ 88] = { 4,	"reboot"					},
	[ 89] = { 3,	"readdir"					},
	[ 90] = { 1,	"mmap"						},
	[ 91] = { 2,	"munmap"					},
	[ 92] = { 2,	"truncate"					},
	[ 93] = { 2,	"ftruncate"					},
	[ 94] = { 2,	"fchmod"					},
	[ 95] = { 3,	"fchown"					},
	[ 96] = { 2,	"getpriority"				},
	[ 97] = { 3,	"setpriority"				},
	[ 98] = { 4,	"profil"					},
	[ 99] = { 2,	"statfs"					},
	[100] = { 2,	"fstatfs"					},
	[101] = { 3,	"ioperm"					},
	[102] = { 2,	"socketcall"				},
	[103] = { 3,	"syslog"					},
	[104] = { 3,	"setitimer"					},
	[105] = { 2,	"getitimer"					},
	[106] = { 2,	"stat"						},
	[107] = { 2,	"lstat"						},
	[108] = { 2,	"fstat"						},
	[109] = { 1,	"olduname"					},
	[110] = { 1,	"iopl"						},
	[111] = { 0,	"vhangup"					},
	[112] = { 0,	"idle"						},
	[113] = { 1,	"vm86old"					},
	[114] = { 4,	"wait4"						},
	[115] = { 1,	"swapoff"					},
	[116] = { 1,	"sysinfo"					},
	[117] = { 6,	"ipc"						},
	[118] = { 1,	"fsync"						},
	[119] = { 0,	"sigreturn"					},
	[120] = { 5,	"clone"						},
	[121] = { 2,	"setdomainname"				},
	[122] = { 1,	"uname"						},
	[123] = { 3,	"modify_ldt"				},
	[124] = { 1,	"adjtimex"					},
	[125] = { 3,	"mprotect"					},
	[126] = { 3,	"sigprocmask"				},
	[127] = { 2,	"create_module"				},
	[128] = { 3,	"init_module"				},
	[129] = { 2,	"delete_module"				},
	[130] = { 1,	"get_kernel_syms"			},
	[131] = { 4,	"quotactl"					},
	[132] = { 1,	"getpgid"					},
	[133] = { 1,	"fchdir"					},
	[134] = { 2,	"bdflush"					},
	[135] = { 3,	"sysfs"						},
	[136] = { 1,	"personality"				},
	[137] = { 5,	"afs_syscall"				},
	[138] = { 1,	"setfsuid"					},
	[139] = { 1,	"setfsgid"					},
	[140] = { 5,	"_llseek"					},
	[141] = { 3,	"getdents"					},
	[142] = { 5,	"_newselect"				},
	[143] = { 2,	"flock"						},
	[144] = { 3,	"msync"						},
	[145] = { 3,	"readv"						},
	[146] = { 3,	"writev"					},
	[147] = { 1,	"getsid"					},
	[148] = { 1,	"fdatasync"					},
	[149] = { 1,	"_sysctl"					},
	[150] = { 2,	"mlock"						},
	[151] = { 2,	"munlock"					},
	[152] = { 1,	"mlockall"					},
	[153] = { 0,	"munlockall"				},
	[154] = { 2,	"sched_setparam"			},
	[155] = { 2,	"sched_getparam"			},
	[156] = { 3,	"sched_setscheduler"		},
	[157] = { 1,	"sched_getscheduler"		},
	[158] = { 0,	"sched_yield"				},
	[159] = { 1,	"sched_get_priority_max"	},
	[160] = { 1,	"sched_get_priority_min"	},
	[161] = { 2,	"sched_rr_get_interval"		},
	[162] = { 2,	"nanosleep"					},
	[163] = { 5,	"mremap"					},
	[164] = { 3,	"setresuid"					},
	[165] = { 3,	"getresuid"					},
	[166] = { 5,	"vm86"						},
	[167] = { 5,	"query_module"				},
	[168] = { 3,	"poll"						},
	[169] = { 3,	"nfsservctl"				},
	[170] = { 3,	"setresgid"					},
	[171] = { 3,	"getresgid"					},
	[172] = { 5,	"prctl"						},
	[173] = { 0,	"rt_sigreturn"				},
	[174] = { 4,	"rt_sigaction"				},
	[175] = { 4,	"rt_sigprocmask"			},
	[176] = { 2,	"rt_sigpending"				},
	[177] = { 4,	"rt_sigtimedwait"			},
	[178] = { 3,	"rt_sigqueueinfo"			},
	[179] = { 2,	"rt_sigsuspend"				},
	[180] = { 5,	"pread64"					},
	[181] = { 5,	"pwrite64"					},
	[182] = { 3,	"chown"						},
	[183] = { 2,	"getcwd"					},
	[184] = { 2,	"capget"					},
	[185] = { 2,	"capset"					},
	[186] = { 2,	"sigaltstack"				},
	[187] = { 4,	"sendfile"					},
	[188] = { 5,	"getpmsg"					},
	[189] = { 5,	"putpmsg"					},
	[190] = { 0,	"vfork"						},
	[191] = { 2,	"ugetrlimit"				},
	[192] = { 6,	"mmap2"						},
	[193] = { 3,	"truncate64"				},
	[194] = { 3,	"ftruncate64"				},
	[195] = { 2,	"stat64"					},
	[196] = { 2,	"lstat64"					},
	[197] = { 2,	"fstat64"					},
	[198] = { 3,	"lchown32"					},
	[199] = { 0,	"getuid32"					},
	[200] = { 0,	"getgid32"					},
	[201] = { 0,	"geteuid32"					},
	[202] = { 0,	"getegid32"					},
	[203] = { 2,	"setreuid32"				},
	[204] = { 2,	"setregid32"				},
	[205] = { 2,	"getgroups32"				},
	[206] = { 2,	"setgroups32"				},
	[207] = { 3,	"fchown32"					},
	[208] = { 3,	"setresuid32"				},
	[209] = { 3,	"getresuid32"				},
	[210] = { 3,	"setresgid32"				},
	[211] = { 3,	"getresgid32"				},
	[212] = { 3,	"chown32"					},
	[213] = { 1,	"setuid32"					},
	[214] = { 1,	"setgid32"					},
	[215] = { 1,	"setfsuid32"				},
	[216] = { 1,	"setfsgid32"				},
	[217] = { 2,	"pivot_root"				},
	[218] = { 3,	"mincore"					},
	[219] = { 3,	"madvise"					},
	[220] = { 3,	"getdents64"				},
	[221] = { 3,	"fcntl64"					},
	[222 ... 223] = { 0,	NULL				},
	[224] = { 0,	"gettid"					},
	[225] = { 4,	"readahead"					},
	[226] = { 5,	"setxattr"					},
	[227] = { 5,	"lsetxattr"					},
	[228] = { 5,	"fsetxattr"					},
	[229] = { 4,	"getxattr"					},
	[230] = { 4,	"lgetxattr"					},
	[231] = { 4,	"fgetxattr"					},
	[232] = { 3,	"listxattr"					},
	[233] = { 3,	"llistxattr"				},
	[234] = { 3,	"flistxattr"				},
	[235] = { 2,	"removexattr"				},
	[236] = { 2,	"lremovexattr"				},
	[237] = { 2,	"fremovexattr"				},
	[238] = { 2,	"tkill"						},
	[239] = { 4,	"sendfile64"				},
	[240] = { 6,	"futex"						},
	[241] = { 3,	"sched_setaffinity"			},
	[242] = { 3,	"sched_getaffinity"			},
	[243] = { 1,	"set_thread_area"			},
	[244] = { 1,	"get_thread_area"			},
	[245] = { 2,	"io_setup"					},
	[246] = { 1,	"io_destroy"				},
	[247] = { 5,	"io_getevents"				},
	[248] = { 3,	"io_submit"					},
	[249] = { 3,	"io_cancel"					},
	[250] = { 5,	"fadvise64"					},
	[251] = { 0,	NULL						}, /* sys_set_zone_reclaim */
	[252] = { 1,	"exit_group"				},
	[253] = { 4,	"lookup_dcookie"			},
	[254] = { 1,	"epoll_create"				},
	[255] = { 4,	"epoll_ctl"					},
	[256] = { 4,	"epoll_wait"				},
	[257] = { 5,	"remap_file_pages"			},
	[258] = { 1,	"set_tid_address"			},
	[259] = { 3,	"timer_create"				},
	[260] = { 4,	"timer_settime"				},
	[261] = { 2,	"timer_gettime"				},
	[262] = { 1,	"timer_getoverrun"			},
	[263] = { 1,	"timer_delete"				},
	[264] = { 2,	"clock_settime"				},
	[265] = { 2,	"clock_gettime"				},
	[266] = { 2,	"clock_getres"				},
	[267] = { 4,	"clock_nanosleep"			},
	[268] = { 3,	"statfs64"					},
	[269] = { 3,	"fstatfs64"					},
	[270] = { 3,	"tgkill"					},
	[271] = { 2,	"utimes"					},
	[272] = { 6,	"fadvise64_64"				},
	[273] = { 5,	"vserver"					},
	[274] = { 6,	"mbind"						},
	[275] = { 5,	"get_mempolicy"				},
	[276] = { 3,	"set_mempolicy"				},
	[277] = { 4,	"mq_open"					},
	[278] = { 1,	"mq_unlink"					},
	[279] = { 5,	"mq_timedsend"				},
	[280] = { 5,	"mq_timedreceive"			},
	[281] = { 2,	"mq_notify"					},
	[282] = { 3,	"mq_getsetattr"				},
	[283] = { 4,	"kexec_load"				},
	[284] = { 5,	"waitid"					},
	[285] = { 0,	NULL						}, /* sys_setaltroot */
	[286] = { 5,	"add_key"					},
	[287] = { 4,	"request_key"				},
	[288] = { 5,	"keyctl"					},
	[289] = { 3,	"ioprio_set"				},
	[290] = { 2,	"ioprio_get"				},
	[291] = { 0,	"inotify_init"				},
	[292] = { 3,	"inotify_add_watch"			},
	[293] = { 2,	"inotify_rm_watch"			},
	[294] = { 4,	"migrate_pages"				},
	[295] = { 4,	"openat"					},
	[296] = { 3,	"mkdirat"					},
	[297] = { 4,	"mknodat"					},
	[298] = { 5,	"fchownat"					},
	[299] = { 3,	"futimesat"					},
	[300] = { 4,	"fstatat64"					},
	[301] = { 3,	"unlinkat"					},
	[302] = { 4,	"renameat"					},
	[303] = { 5,	"linkat"					},
	[304] = { 3,	"symlinkat"					},
	[305] = { 4,	"readlinkat"				},
	[306] = { 3,	"fchmodat"					},
	[307] = { 3,	"faccessat"					},
	[308] = { 6,	"pselect6"					},
	[309] = { 5,	"ppoll"						},
	[310] = { 1,	"unshare"					},
	[311] = { 2,	"set_robust_list"			},
	[312] = { 3,	"get_robust_list"			},
	[313] = { 6,	"splice"					},
	[314] = { 6,	"sync_file_range"			},
	[315] = { 4,	"tee"						},
	[316] = { 4,	"vmsplice"					},
	[317] = { 6,	"move_pages"				},
	[318] = { 3,	"getcpu"					},
	[319] = { 6,	"epoll_pwait"				},
	[320] = { 4,	"utimensat"					},
	[321] = { 3,	"signalfd"					},
	[322] = { 2,	"timerfd_create"			},
	[323] = { 1,	"eventfd"					},
	[324] = { 6,	"fallocate"					},
	[325] = { 4,	"timerfd_settime"			},
	[326] = { 2,	"timerfd_gettime"			},
	[327] = { 4,	"signalfd4"					},
	[328] = { 2,	"eventfd2"					},
	[329] = { 1,	"epoll_create1"				},
	[330] = { 3,	"dup3"						},
	[331] = { 2,	"pipe2"						},
	[332] = { 1,	"inotify_init1"				},
	[333] = { 5,	"preadv"					},
	[334] = { 5,	"pwritev"					},
	[335] = { 4,	"rt_tgsigqueueinfo"			},
	[336] = { 5,	"perf_event_open"			},
	[337] = { 5,	"recvmmsg"					},
	[338] = { 2,	"fanotify_init"				},
	[339] = { 6,	"fanotify_mark"				},
	[340] = { 4,	"prlimit64"					},
	[341] = { 5,	"name_to_handle_at"			},
	[342] = { 3,	"open_by_handle_at"			},
	[343] = { 2,	"clock_adjtime"				},
	[344] = { 1,	"syncfs"					},
	[345] = { 4,	"sendmmsg"					},
	[346] = { 2,	"setns"						},
	[347] = { 6,	"process_vm_readv"			},
	[348] = { 6,	"process_vm_writev"			},
	[349] = { 5,	"kcmp"						},
	[350] = { 3,	"finit_module"				},
	[351] = { 3,	"sched_setattr"				},
	[352] = { 4,	"sched_getattr"				},
	[353] = { 5,	"renameat2"					},
	[354] = { 3,	"seccomp"					},
	[355] = { 3,	"getrandom"					},
	[356] = { 2,	"memfd_create"				},
	[357] = { 3,	"bpf"						},
	[358] = { 5,	"execveat"					},
	[359] = { 3,	"socket"					},
	[360] = { 4,	"socketpair"				},
	[361] = { 3,	"bind"						},
	[362] = { 3,	"connect"					},
	[363] = { 2,	"listen"					},
	[364] = { 4,	"accept4"					},
	[365] = { 5,	"getsockopt"				},
	[366] = { 5,	"setsockopt"				},
	[367] = { 3,	"getsockname"				},
	[368] = { 3,	"getpeername"				},
	[369] = { 6,	"sendto"					},
	[370] = { 3,	"sendmsg"					},
	[371] = { 6,	"recvfrom"					},
	[372] = { 3,	"recvmsg"					},
	[373] = { 2,	"shutdown"					},
	[374] = { 1,	"userfaultfd"				},
	[375] = { 3,	"membarrier"				},
	[376] = { 3,	"mlock2"					},
	[377] = { 6,	"copy_file_range"			},
	[378] = { 6,	"preadv2"					},
	[379] = { 6,	"pwritev2"					},
	[380] = { 4,	"pkey_mprotect"				},
	[381] = { 2,	"pkey_alloc"				},
	[382] = { 1,	"pkey_free"					},
	[383] = { 5,	"statx"						},
	[384] = { 2,	"arch_prctl"				},
	[385] = { 6,	"io_pgetevents"				},
	[386] = { 4,	"rseq"						},
	[387 ... 392] = { 0,	NULL				},	/* room for arch specific calls */
	[393] = { 3,	"semget"					},
	[394] = { 4,	"semctl"					},
	[395] = { 3,	"shmget"					},
	[396] = { 3,	"shmctl"					},
	[397] = { 3,	"shmat"						},
	[398] = { 1,	"shmdt"						},
	[399] = { 2,	"msgget"					},
	[400] = { 4,	"msgsnd"					},
	[401] = { 5,	"msgrcv"					},
	[402] = { 3,	"msgctl"					},
};

t_syscall	g_syscall_64[] = {
	{ 3,	"read"						},
	{ 3,	"write"						},
	{ 3,	"open"						},
	{ 1,	"close"						},
	{ 2,	"stat"						},
	{ 2,	"fstat"						},
	{ 2,	"lstat"						},
	{ 3,	"poll"						},
	{ 3,	"lseek"						},
	{ 6,	"mmap"						},
	{ 3,	"mprotect"					},
	{ 2,	"munmap"					},
	{ 1,	"brk"						},
	{ 4,	"rt_sigaction"				},
	{ 4,	"rt_sigprocmask"			},
	{ 0,	"rt_sigreturn"				},
	{ 3,	"ioctl"						},
	{ 4,	"pread64"					},
	{ 4,	"pwrite64"					},
	{ 3,	"readv"						},
	{ 3,	"writev"					},
	{ 2,	"access"					},
	{ 1,	"pipe"						},
	{ 5,	"select"					},
	{ 0,	"sched_yield"				},
	{ 5,	"mremap"					},
	{ 3,	"msync"						},
	{ 3,	"mincore"					},
	{ 3,	"madvise"					},
	{ 3,	"shmget"					},
	{ 3,	"shmat"						},
	{ 3,	"shmctl"					},
	{ 1,	"dup"						},
	{ 2,	"dup2"						},
	{ 0,	"pause"						},
	{ 2,	"nanosleep"					},
	{ 2,	"getitimer"					},
	{ 1,	"alarm"						},
	{ 3,	"setitimer"					},
	{ 0,	"getpid"					},
	{ 4,	"sendfile"					},
	{ 3,	"socket"					},
	{ 3,	"connect"					},
	{ 3,	"accept"					},
	{ 6,	"sendto"					},
	{ 6,	"recvfrom"					},
	{ 3,	"sendmsg"					},
	{ 3,	"recvmsg"					},
	{ 2,	"shutdown"					},
	{ 3,	"bind"						},
	{ 2,	"listen"					},
	{ 3,	"getsockname"				},
	{ 3,	"getpeername"				},
	{ 4,	"socketpair"				},
	{ 5,	"setsockopt"				},
	{ 5,	"getsockopt"				},
	{ 5,	"clone"						},
	{ 0,	"fork"						},
	{ 0,	"vfork"						},
	{ 3,	"execve"					},
	{ 1,	"exit"						},
	{ 4,	"wait4"						},
	{ 2,	"kill"						},
	{ 1,	"uname"						},
	{ 3,	"semget"					},
	{ 3,	"semop"						},
	{ 4,	"semctl"					},
	{ 1,	"shmdt"						},
	{ 2,	"msgget"					},
	{ 4,	"msgsnd"					},
	{ 5,	"msgrcv"					},
	{ 3,	"msgctl"					},
	{ 3,	"fcntl"						},
	{ 2,	"flock"						},
	{ 1,	"fsync"						},
	{ 1,	"fdatasync"					},
	{ 2,	"truncate"					},
	{ 2,	"ftruncate"					},
	{ 3,	"getdents"					},
	{ 2,	"getcwd"					},
	{ 1,	"chdir"						},
	{ 1,	"fchdir"					},
	{ 2,	"rename"					},
	{ 2,	"mkdir"						},
	{ 1,	"rmdir"						},
	{ 2,	"creat"						},
	{ 2,	"link"						},
	{ 1,	"unlink"					},
	{ 2,	"symlink"					},
	{ 3,	"readlink"					},
	{ 2,	"chmod"						},
	{ 2,	"fchmod"					},
	{ 3,	"chown"						},
	{ 3,	"fchown"					},
	{ 3,	"lchown"					},
	{ 1,	"umask"						},
	{ 2,	"gettimeofday"				},
	{ 2,	"getrlimit"					},
	{ 2,	"getrusage"					},
	{ 1,	"sysinfo"					},
	{ 1,	"times"						},
	{ 4,	"ptrace"					},
	{ 0,	"getuid"					},
	{ 3,	"syslog"					},
	{ 0,	"getgid"					},
	{ 1,	"setuid"					},
	{ 1,	"setgid"					},
	{ 0,	"geteuid"					},
	{ 0,	"getegid"					},
	{ 2,	"setpgid"					},
	{ 0,	"getppid"					},
	{ 0,	"getpgrp"					},
	{ 0,	"setsid"					},
	{ 2,	"setreuid"					},
	{ 2,	"setregid"					},
	{ 2,	"getgroups"					},
	{ 2,	"setgroups"					},
	{ 3,	"setresuid"					},
	{ 3,	"getresuid"					},
	{ 3,	"setresgid"					},
	{ 3,	"getresgid"					},
	{ 1,	"getpgid"					},
	{ 1,	"setfsuid"					},
	{ 1,	"setfsgid"					},
	{ 1,	"getsid"					},
	{ 2,	"capget"					},
	{ 2,	"capset"					},
	{ 2,	"rt_sigpending"				},
	{ 4,	"rt_sigtimedwait"			},
	{ 3,	"rt_sigqueueinfo"			},
	{ 2,	"rt_sigsuspend"				},
	{ 2,	"sigaltstack"				},
	{ 2,	"utime"						},
	{ 3,	"mknod"						},
	{ 1,	"uselib"					},
	{ 1,	"personality"				},
	{ 2,	"ustat"						},
	{ 2,	"statfs"					},
	{ 2,	"fstatfs"					},
	{ 3,	"sysfs"						},
	{ 2,	"getpriority"				},
	{ 3,	"setpriority"				},
	{ 2,	"sched_setparam"			},
	{ 2,	"sched_getparam"			},
	{ 3,	"sched_setscheduler"		},
	{ 1,	"sched_getscheduler"		},
	{ 1,	"sched_get_priority_max"	},
	{ 1,	"sched_get_priority_min"	},
	{ 2,	"sched_rr_get_interval"		},
	{ 2,	"mlock"						},
	{ 2,	"munlock"					},
	{ 1,	"mlockall"					},
	{ 0,	"munlockall"				},
	{ 0,	"vhangup"					},
	{ 3,	"modify_ldt"				},
	{ 2,	"pivot_root"				},
	{ 1,	"_sysctl"					},
	{ 5,	"prctl"						},
	{ 2,	"arch_prctl"				},
	{ 1,	"adjtimex"					},
	{ 2,	"setrlimit"					},
	{ 1,	"chroot"					},
	{ 0,	"sync"						},
	{ 1,	"acct"						},
	{ 2,	"settimeofday"				},
	{ 5,	"mount"						},
	{ 2,	"umount2"					},
	{ 2,	"swapon"					},
	{ 1,	"swapoff"					},
	{ 4,	"reboot"					},
	{ 2,	"sethostname"				},
	{ 2,	"setdomainname"				},
	{ 1,	"iopl"						},
	{ 3,	"ioperm"					},
	{ 2,	"create_module"				},
	{ 3,	"init_module"				},
	{ 2,	"delete_module"				},
	{ 1,	"get_kernel_syms"			},
	{ 5,	"query_module"				},
	{ 4,	"quotactl"					},
	{ 3,	"nfsservctl"				},
	{ 5,	"getpmsg"					},
	{ 5,	"putpmsg"					},
	{ 5,	"afs_syscall"				},
	{ 3,	"tuxcall"					},
	{ 3,	"security"					},
	{ 0,	"gettid"					},
	{ 3,	"readahead"					},
	{ 5,	"setxattr"					},
	{ 5,	"lsetxattr"					},
	{ 5,	"fsetxattr"					},
	{ 4,	"getxattr"					},
	{ 4,	"lgetxattr"					},
	{ 4,	"fgetxattr"					},
	{ 3,	"listxattr"					},
	{ 3,	"llistxattr"				},
	{ 3,	"flistxattr"				},
	{ 2,	"removexattr"				},
	{ 2,	"lremovexattr"				},
	{ 2,	"fremovexattr"				},
	{ 2,	"tkill"						},
	{ 1,	"time"						},
	{ 6,	"futex"						},
	{ 3,	"sched_setaffinity"			},
	{ 3,	"sched_getaffinity"			},
	{ 1,	"set_thread_area"			},
	{ 2,	"io_setup"					},
	{ 1,	"io_destroy"				},
	{ 5,	"io_getevents"				},
	{ 3,	"io_submit"					},
	{ 3,	"io_cancel"					},
	{ 1,	"get_thread_area"			},
	{ 3,	"lookup_dcookie"			},
	{ 1,	"epoll_create"				},
	{ 4,	"epoll_ctl_old"				},
	{ 4,	"epoll_wait_old"			},
	{ 5,	"remap_file_pages"			},
	{ 3,	"getdents64"				},
	{ 1,	"set_tid_address"			},
	{ 0,	"restart_syscall"			},
	{ 4,	"semtimedop"				},
	{ 4,	"fadvise64"					},
	{ 3,	"timer_create"				},
	{ 4,	"timer_settime"				},
	{ 2,	"timer_gettime"				},
	{ 1,	"timer_getoverrun"			},
	{ 1,	"timer_delete"				},
	{ 2,	"clock_settime"				},
	{ 2,	"clock_gettime"				},
	{ 2,	"clock_getres"				},
	{ 4,	"clock_nanosleep"			},
	{ 1,	"exit_group"				},
	{ 4,	"epoll_wait"				},
	{ 4,	"epoll_ctl"					},
	{ 3,	"tgkill"					},
	{ 2,	"utimes"					},
	{ 5,	"vserver"					},
	{ 6,	"mbind"						},
	{ 3,	"set_mempolicy"				},
	{ 5,	"get_mempolicy"				},
	{ 4,	"mq_open"					},
	{ 1,	"mq_unlink"					},
	{ 5,	"mq_timedsend"				},
	{ 5,	"mq_timedreceive"			},
	{ 2,	"mq_notify"					},
	{ 3,	"mq_getsetattr"				},
	{ 4,	"kexec_load"				},
	{ 5,	"waitid"					},
	{ 5,	"add_key"					},
	{ 4,	"request_key"				},
	{ 5,	"keyctl"					},
	{ 3,	"ioprio_set"				},
	{ 2,	"ioprio_get"				},
	{ 0,	"inotify_init"				},
	{ 3,	"inotify_add_watch"			},
	{ 2,	"inotify_rm_watch"			},
	{ 4,	"migrate_pages"				},
	{ 4,	"openat"					},
	{ 3,	"mkdirat"					},
	{ 4,	"mknodat"					},
	{ 5,	"fchownat"					},
	{ 3,	"futimesat"					},
	{ 4,	"newfstatat"				},
	{ 3,	"unlinkat"					},
	{ 4,	"renameat"					},
	{ 5,	"linkat"					},
	{ 3,	"symlinkat"					},
	{ 4,	"readlinkat"				},
	{ 3,	"fchmodat"					},
	{ 3,	"faccessat"					},
	{ 6,	"pselect6"					},
	{ 5,	"ppoll"						},
	{ 1,	"unshare"					},
	{ 2,	"set_robust_list"			},
	{ 3,	"get_robust_list"			},
	{ 6,	"splice"					},
	{ 4,	"tee"						},
	{ 4,	"sync_file_range"			},
	{ 4,	"vmsplice"					},
	{ 6,	"move_pages"				},
	{ 4,	"utimensat"					},
	{ 6,	"epoll_pwait"				},
	{ 3,	"signalfd"					},
	{ 2,	"timerfd_create"			},
	{ 1,	"eventfd"					},
	{ 4,	"fallocate"					},
	{ 4,	"timerfd_settime"			},
	{ 2,	"timerfd_gettime"			},
	{ 4,	"accept4"					},
	{ 4,	"signalfd4"					},
	{ 2,	"eventfd2"					},
	{ 1,	"epoll_create1"				},
	{ 3,	"dup3"						},
	{ 2,	"pipe2"						},
	{ 1,	"inotify_init1"				},
	{ 4,	"preadv"					},
	{ 4,	"pwritev"					},
	{ 4,	"rt_tgsigqueueinfo"			},
	{ 5,	"perf_event_open"			},
	{ 5,	"recvmmsg"					},
	{ 2,	"fanotify_init"				},
	{ 5,	"fanotify_mark"				},
	{ 4,	"prlimit64"					},
	{ 5,	"name_to_handle_at"			},
	{ 3,	"open_by_handle_at"			},
	{ 2,	"clock_adjtime"				},
	{ 1,	"syncfs"					},
	{ 4,	"sendmmsg"					},
	{ 2,	"setns"						},
	{ 3,	"getcpu"					},
	{ 6,	"process_vm_readv"			},
	{ 6,	"process_vm_writev"			},
	{ 5,	"kcmp"						},
	{ 3,	"finit_module"				},
	{ 3,	"sched_setattr"				},
	{ 4,	"sched_getattr"				},
	{ 5,	"renameat2"					},
	{ 3,	"seccomp"					},
	{ 3,	"getrandom"					},
	{ 2,	"memfd_create"				},
	{ 5,	"kexec_file_load"			},
	{ 3,	"bpf"						},
	{ 5,	"execveat"					},
	{ 1,	"userfaultfd"				},
	{ 3,	"membarrier"				},
	{ 3,	"mlock2"					},
	{ 6,	"copy_file_range"			},
	{ 6,	"preadv2"					},
	{ 6,	"pwritev2"					},
	{ 4,	"pkey_mprotect"				},
	{ 2,	"pkey_alloc"				},
	{ 1,	"pkey_free"					},
	{ 5,	"statx"						},
	{ 6,	"io_pgetevents"				},
	{ 4,	"rseq"						},
};
